### ISSUE TITLE
asset support (images, downloads, etc.)

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/sphinxcontrib-confluencebuilder#131]
This issue has been created to track the progress of [image](http://docutils.sourceforge.net/docs/ref/rst/directives.html#images)/[download](http://www.sphinx-doc.org/en/stable/markup/inline.html#role-download) support for this extension. There is currently no estimated time when this capability will be available as part as a stable release for this extension. As development proceeds, this ticket will be updated with the most recent information known until the feature is merged in and made available in a release.

- [x] (pre-push requirement) Ensure select commits from "storage format conversion (and more)" are merged in (#121).
- [x] (pre-push requirement) Ensure select commits from "purge improvements" are merged in (#125).
- [X] Support uploading assets from a documentation set into Confluence:
    - [X] Creating or updating images/files using:
        - [X] REST
        - [X] XML-RPC
    - [X] Ability to track and purge legacy assets using:
        - [X] REST
        - [X] XML-RPC
- [x] Support rendering download and image-based content in published documents:
    - [X] Support simple image blocks.
    - [X] Support label-based links to images.
    - [x] Support wrapping image blocks with references (links; see #132).
    - [X] Ability to display link for explicit download references.
    - [X] Ability to display "view-file" macro for non-explicit download references.
    - [X] Support the figure directive.
- [x] Finalize unit tests for:
    - [x] Download directive validation.
    - [x] Image directive validation.
    - [x] Figure directive validation.
- [x] Add a validation test for images and download directives.
    - [x] Validation on Confluence Cloud
    - [x] Validation on Confluence Server
- [x] Add new asset-based configuration options to documentation.
- [x] Update markup documentation.
- [x] Submitted for review and merged in.

**Comment by jdknight** [comment]
See also pull request #135.

**Comment by keesj** [comment]
Tested the head branch by installing the git master version e.g. 
following https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/blob/master/doc/install.rst#master

So far things are looking quite good (image upload works) and most of the linking also does.

**Comment by jdknight** [comment]
Version 1.0 of this extension has been released which includes asset management; closing.
